# Generated by Django 3.1.7 on 2021-03-31 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='achivement',
            field=models.CharField(choices=[('US', 'United States'), ('FR', 'France'), ('CN', 'China'), ('RU', 'Russia'), ('IT', 'Italy')], default='US', max_length=2),
        ),
    ]
